export const EPIC_KEY = {
  DASHBOARD: 'dashboard',
  EMPLOYEE_LIST: 'employee_list',
  INSURANCE: 'insurance',
  EMPLOYEE_GROUP: 'employee_group',
  CONTRACT: 'contract',
  SALARY: 'salary',
  RECRUITMENT_PLANS: 'recruitment_plan',
  RECRUITMENT_CRITERIA: 'recruitment_criteria',
  RECRUITMENT_CANDIDATE: 'recruitment_candidate',
  RECRUITMENT_POSITION: 'recruitment_position',
  RECRUITMENT_NEEDS: 'recruitment_needs',
  TIME_SHEET: 'time_sheet',
  EMPLOYEE_SHIFT: 'employee_shift',
  OVER_TIME_SHEET: 'over_time_sheet',
  DAY_OFF: 'day_off',
  OVERTIME_APPLICATION: 'overtime_application',
  BUSINESS_TRIP_APPLICATION: 'business_trip_application',
  LEAVE_CONFIG: 'leave_config',
  ANNUAL_LEAVE: 'annual_leave',
  LEAVE_REPORT: 'leave_report',
  OVERTIME_FORM: 'overtime_form',
  LEAVE_APPLICATION: 'leave_application',
  PRE_LEAVE_APPLICATION: 'pre_leave_application',
  OVERTIME_BREAK: 'overtime_break',
  EXTRA_ATTENDANCE_APPLICATION: 'extra_attendance_application',
  CONFIG_DATA: 'config_data',
  CONFIG_STATUS: 'config_status',
  CONFIG_APPLICATION: 'config_application',
  CONFIG_DEPARTMENT: 'config_department',
  CONFIG_POSITION: 'config_position',
  CONFIG_JOB_TITLE: 'config_job_title',
  CONFIG_PERMISSION: 'config_permission',
  MANAGE_PAGE: 'manage_page',
  CONTACT_MANAGEMENT_EMPLOYEE: 'contact_management_employee',
  CONTACT_MANAGEMENT_SUPPLIER: 'contact_management_supplier',
  CONTACT_MANAGEMENT_CUSTOMER: 'contact_management_customer',
};

export const PAGE_KEY = {
  DASHBOARD_LIST_VIEW: 'hrm_dashboard_list_view',
  DASHBOARD_LIST_CREATE: 'hrm_dashboard_list_create',
  EMPLOYEE_LIST_VIEW: 'hrm_employee_list_view',
  EMPLOYEE_LIST_CREATE: 'hrm_employee_list_create',
  EMPLOYEE_LIST_UPDATE: 'hrm_employee_list_update',
  EMPLOYEE_LIST_DETAIL: 'hrm_employee_list_detail',
  INSURANCE_LIST_VIEW: 'hrm_insurance_list_view',
  INSURANCE_LIST_CREATE: 'hrm_insurance_list_create',
  INSURANCE_LIST_UPDATE: 'hrm_insurance_List_update',
  INSURANCE_LIST_DETAIL: 'hrm_insurance_List_detail',
  EMPLOYEE_GROUP_LIST_VIEW: 'hrm_employee_group_list_view',
  CONTRACT_LIST_VIEW: 'hrm_contract_list_view',
  CONTRACT_LIST_CREATE: 'hrm_contract_list_create',
  CONTRACT_LIST_UPDATE: 'hrm_contract_list_update',
  CONTRACT_LIST_DETAIL: 'hrm_contract_list_detail',
  SALARY_LIST_VIEW: 'hrm_salary_list_view',
  SALARY_LIST_CREATE: 'hrm_salary_list_create',
  SALARY_LIST_UPDATE: 'hrm_salary_list_update',
  SALARY_LIST_DETAIL: 'hrm_salary_list_detail',
  PLANS_LIST_VIEW: 'hrm_plans_list_view',
  PLANS_LIST_VACANCIES_LIST: 'hrm_plans_list_vacancies_list',
  PLANS_LIST_SUBMISSION: 'hrm_plans_list_submission',
  CRITERIA_LIST_VIEW: 'hrm_criteria_list_view',
  CANDIDATE_LIST_VIEW: 'hrm_candidate_list_view',
  CANDIDATE_LIST_CREATE: 'hrm_candidate_list_create',
  CANDIDATE_LIST_UPDATE: 'hrm_candidate_list_update',
  CANDIDATE_LIST_DETAIL: 'hrm_candidate_list_detail',
  POSITION_LIST_VIEW: 'hrm_position_list_view',
  POSITION_LIST_DETAIL: 'hrm_position_list_detail',
  NEEDS_LIST_VIEW: 'hrm_needs_list_view',
  NEEDS_LIST_DETAIL: 'hrm_needs_list_detail',
  TIME_SHEET_LIST_VIEW: 'hrm_time_sheet_list_view',
  OVER_TIME_SHEET_LIST_VIEW: 'hrm_over_time_sheet_list_view',
  OVER_TIME_SHEET_LIST_DETAIL: 'hrm_over_time_sheet_list_detail',
  EMPLOYEE_SHIFT_LIST_VIEW: 'hrm_employee_shift_list_view',
  EMPLOYEE_SHIFT_LIST_DETAIL: 'hrm_employee_shift_list_detail',
  LIST_EMPLOYEE_IN_THE_SHIFT: 'hrm_list_employee_in_the_shift',
  DAY_OFF_LIST_VIEW: 'hrm_day_off_list_view',
  OVERTIME_APPLICATION_LIST_VIEW: 'hrm_overtime_application_list_view',
  EXTRA_ATTENDANCE_FORM_LIST_VIEW: 'hrm_extra_attendance_form_list_view',
  LEAVE_CONFIG_LIST_VIEW: 'hrm_leave_config_list_view',
  LEAVE_CONFIG_LIST_VIEW_DETAIL: 'hrm_leave_config_list_view_detail',
  EXTRA_ATTENDANCE_APPLICATION_LIST_VIEW:
    'hrm_extra_attendance_application_list_view',
  LEAVE_APPLICATION_LIST_VIEW: 'hrm_leave_application_list_view',
  BUSINESS_TRIP_APPLICATION_LIST_VIEW: 'hrm_business_trip_list_view',
  PRE_LEAVE_APPLICATION_LIST_VIEW: 'hrm_pre_leave_application_list_view',
  ANNUAL_LEAVE_LIST_VIEW: 'hrm_annual_leave_list_view',
  ANNUAL_LEAVE_LIST_VIEW_DETAIL: 'hrm_annual_leave_list_view_detail',
  OVERTIME_BREAK_LIST_VIEW: 'hrm_overtime_break_list_view',
  OVERTIME_BREAK_LIST_VIEW_DETAIL: 'hrm_overtime_break_list_view_detail',
  LEAVE_REPORT_LIST_VIEW: 'hrm_leave_report_list_view',
  CONFIG_DATA_LIST_VIEW: 'hrm_config_data_list_view',
  CONFIG_STATUS_LIST_VIEW: 'hrm_config_status_list_view',
  CONFIG_APPLICATION_LIST_VIEW: 'hrm_config_application_list_view',
  CONFIG_DEPARTMENT_LIST_VIEW: 'hrm_config_department_list_view',
  CONFIG_POSITION_LIST_VIEW: 'hrm_config_position_list_view',
  CONFIG_JOB_TITLE_LIST_VIEW: 'hrm_config_job_title_list_view',
  CONFIG_PERMISSION_LIST_VIEW: 'hrm_config_permission_list_view',
  CONFIG_PERMISSION_LIST_SETTING: 'hrm_config_permission_list_setting',
  MANAGE_PAGE_LIST_VIEW: 'hrm_manage_page_list_view',
  MANAGE_PAGE_CONFIG_FORM: 'hrm_manage_page_config_form',
  MANAGE_PAGE_CONFIG_FORM_DETAIL: 'hrm_manage_page_config_form_detail',
  MANAGE_PAGE_CONFIG_FIELD: 'hrm_manage_page_config_field',
  MANAGE_PAGE_TABLE_CONFIG: 'hrm_manage_page_table_config',
  MANAGE_PAGE_TABLE_CONFIG_DETAIL: 'hrm_manage_page_table_config_detail',
  MANAGE_PAGE_LIST_VIEW_DETAIL: 'hrm_manage_page_list_view_detail',
  COLUMN_CONFIG_LIST_VIEW: 'hrm_column_config_list_view',
  MANAGE_PAGE_CONTROL_CONFIG: 'hrm_manage_page_control_config',

  PURCHASE_MANAGEMENT_LIST_VIEW: 'purchase_management_list_view',
  PURCHASE_MANAGEMENT_LIST_CREATE: 'purchase_management_list_create',
  PURCHASE_MANAGEMENT_LIST_DETAIL: 'purchase_management_list_detail',
  PURCHASE_MANAGEMENT_LIST_UPDATE: 'purchase_management_list_update',

  CONTACT_MANAGEMENT_EMPLOYEE_LIST_VIEW:
    'crm_contact_management_employee_list_view',
  CONTACT_MANAGEMENT_EMPLOYEE_LIST_VIEW_DETAIL:
    'crm_contact_management_employee_list_view_detail',
  CONTACT_MANAGEMENT_EMPLOYEE_LIST_VIEW_CREATE:
    'crm_contact_management_employee_list_view_create',
  CONTACT_MANAGEMENT_EMPLOYEE_LIST_VIEW_UPDATE:
    'crm_contact_management_employee_list_view_update',
  CONTACT_MANAGEMENT_SUPPLIER_LIST_VIEW:
    'crm_contact_management_supplier_list_view',
  CONTACT_MANAGEMENT_SUPPLIER_LIST_VIEW_CREATE:
    'crm_contact_management_supplier_list_view_create',
  CONTACT_MANAGEMENT_SUPPLIER_LIST_VIEW_UPDATE:
    'crm_contact_management_supplier_list_view_update',
  CONTACT_MANAGEMENT_SUPPLIER_LIST_VIEW_DETAIL:
    'crm_contact_management_supplier_list_view_detail',
  CONTACT_MANAGEMENT_CUSTOMER_LIST_VIEW:
    'crm_contact_management_customer_list_view',
  PRODUCT_MANAGEMENT_LIST_VIEW: 'product_management_list_view',
  PRODUCT_MANAGEMENT_CREATE: 'product_management_create',
  PRODUCT_MANAGEMENT_UPDATE: 'product_management_update',
  PRODUCT_MANAGEMENT_DETAIL: 'product_management_detail',
  PRODUCT_MANAGEMENT_HISTORY_TRADE: 'product_management_history_trade',
  PRODUCT_MANAGEMENT_CATEGORY_LIST: 'product_management_category_list',
  PRODUCT_MANAGEMENT_CATEGORY_DETAIL: 'product_management_category_detail',
  PRODUCT_MANAGEMENT_BRAND_LIST: 'product_management_brand_list',
  PRODUCT_MANAGEMENT_UNIT_LIST: 'product_management_unit_list',
  CONTACT_MANAGEMENT_CUSTOMER_LIST_VIEW_CREATE:
    'crm_contact_management_customer_list_view_create',
  CONTACT_MANAGEMENT_CUSTOMER_LIST_VIEW_UPDATE:
    'crm_contact_management_customer_list_view_update',
  CONTACT_MANAGEMENT_CUSTOMER_LIST_VIEW_DETAIL:
    'crm_contact_management_customer_list_view_detail',
  PRICE_QUOTATION_LIST_VIEW: 'crm_price_quote_list_view',
  PRICE_QUOTATION_LIST_VIEW_CREATE: 'crm_price_quote_list_view_create',
  PRICE_QUOTATION_LIST_VIEW_UPDATE: 'crm_price_quote_list_view_update',
  PRICE_QUOTATION_LIST_VIEW_DETAIL: 'crm_price_quote_list_view_detail',

  PURCHASE_REQUEST_LIST_VIEW: 'crm_purchase_request_list_view',
  PURCHASE_REQUEST_LIST_CREATE: 'crm_purchase_request_list_view_create',
  PURCHASE_REQUEST_LIST_UPDATE: 'crm_purchase_request_list_view_update',
  PURCHASE_REQUEST_LIST_DETAIL: 'crm_purchase_request_list_view_detail',

  DELIVERY_SELL_LIST_VIEW: 'crm_delivery_sell_list_view',
  DELIVERY_SELL_LIST_CREATE: 'crm_delivery_sell_list_create',
  DELIVERY_SELL_LIST_DETAIL: 'crm_delivery_sell_list_detail',

  DELIVERY_PURCHASE_LIST_VIEW: 'crm_delivery_purchase_list_view',
  DELIVERY_PURCHASE_LIST_CREATE: 'crm_delivery_purchase_list_create',
  DELIVERY_PURCHASE_LIST_DETAIL: 'crm_delivery_purchase_list_detail',

  SETTING_CONFIG_LIST_VIEW: 'crm_setting_config_list_view',
  PURCHASE_ORDER_LIST_VIEW: 'purchase-order-list-view',
  PURCHASE_ORDER_LIST_DETAIL: 'purchase-order-list-detail',
  PURCHASE_ORDER_LIST_PAYMENT: 'purchase-order-list-payment',

  SALES_ORDER_LIST_VIEW: 'purchase-order-list-view',
  SALES_ORDER_LIST_DETAIL: 'purchase-order-list-detail',
  SALES_ORDER_LIST_PAYMENT: 'purchase-order-list-payment',
  DELIVERY_COMPANY_LIST_VIEW: 'delivery-company-list-view',

  PURCHASE_RETURN_LIST_VIEW: 'crm_purchase_return_list_view',
  PURCHASE_RETURN_LIST_CREATE: 'crm_purchase_return_list_view_create',
  PURCHASE_RETURN_LIST_UPDATE: 'crm_purchase_return_list_view_update',
  PURCHASE_RETURN_LIST_DETAIL: 'crm_purchase_return_list_view_detail',
};

export const TABLE_KEY = {
  EMPLOYEE_LIST_VIEW_EMPLOYEE: 'employee_list_view_employee',
  EMPLOYEE_LIST_DETAIL_CONTRACT: 'employee_list_detail_contract',
  EMPLOYEE_LIST_DETAIL_INSURANCE: 'employee_list_detail_insurance',
  EMPLOYEE_LIST_DETAIL_SALARY: 'employee_list_detail_salary',
  EMPLOYEE_LIST_DETAIL_PROFILE: 'employee_list_detail_profile',
  EMPLOYEE_LIST_DETAIL_STATUS: 'employee_list_detail_status',
  EMPLOYEE_LIST_DETAIL_RELATIONSHIP: 'employee_list_detail_relationship',
  EMPLOYEE_LIST_DETAIL_EXPERIENCE: 'employee_list_detail_experience',
  EMPLOYEE_LIST_DETAIL_CERTIFICATION: 'employee_list_detail_certification',
  EMPLOYEE_LIST_DETAIL_DEGREE: 'employee_list_detail_degree',
  EMPLOYEE_GROUP_LIST_VIEW_GROUP_EMPLOYEE:
    'hrm_employee_group_list_view_group_employee',
};

export const BUTTON_KEY = {
  EMPLOYEE_LIST_CREATE: 'employee_list_create',
  EMPLOYEE_LIST_UPDATE: 'employee_list_update',
  EMPLOYEE_LIST_DETAIL: 'employee_list_detail',
  EMPLOYEE_LIST_DELETE: 'employee_list_delete',
  INSURANCE_LIST_CREATE: 'insurance_list_create',
  INSURANCE_LIST_UPDATE: 'insurance_List_update',
  INSURANCE_LIST_DETAIL: 'insurance_List_detail',
  INSURANCE_LIST_DELETE: 'insurance_List_delete',
  CONTRACT_LIST_CREATE: 'contract_list_create',
  CONTRACT_LIST_UPDATE: 'contract_list_update',
  CONTRACT_LIST_DETAIL: 'contract_list_detail',
  CONTRACT_LIST_DELETE: 'contract_list_delete',
  SALARY_LIST_CREATE: 'salary_list_create',
  SALARY_LIST_UPDATE: 'salary_list_update',
  SALARY_LIST_DETAIL: 'salary_list_detail',
  SALARY_LIST_DELETE: 'salary_list_delete',
  EMPLOYEE_GROUP_LIST_CREATE: 'employee_group_list_create',
  EMPLOYEE_GROUP_LIST_UPDATE: 'employee_group_list_update',
  EMPLOYEE_GROUP_LIST_DETAIL: 'employee_group_list_detail',
  EMPLOYEE_GROUP_LIST_DELETE: 'employee_group_list_delete',
  PLANS_LIST_CREATE: 'plans_list_create',
  PLANS_LIST_DETAIL: 'plans_list_detail',
  PLANS_LIST_VACANCIES_LIST: 'plans_list_vacancies_list',
  PLANS_LIST_SUBMISSION: 'plans_list_submission',
  PLANS_LIST_UPDATE: 'plans_list_update',
  PLANS_LIST_DELETE: 'plans_list_delete',
  CRITERIA_LIST_CREATE: 'criteria_list_create',
  CRITERIA_LIST_UPDATE: 'criteria_list_update',
  CRITERIA_LIST_DETAIL: 'criteria_list_detail',
  CRITERIA_LIST_DELETE: 'criteria_list_delete',
  CANDIDATE_LIST_CREATE: 'candidate_list_create',
  CANDIDATE_LIST_UPDATE: 'candidate_list_update',
  CANDIDATE_LIST_DETAIL: 'candidate_list_detail',
  CANDIDATE_LIST_DELETE: 'candidate_list_delete',
  CANDIDATE_LIST_STATUS_UPDATE: 'candidate_list_status_update',
  POSITION_LIST_CREATE: 'position_list_create',
  POSITION_LIST_DETAIL: 'position_list_detail',
  POSITION_LIST_UPDATE: 'position_list_update',
  POSITION_LIST_DELETE: 'position_list_delete',
  POSITION_LIST_CRITERIA_UPDATE: 'position_list_criteria_update',
  NEEDS_LIST_DETAIL: 'needs_list_detail',
  TIME_SHEET_LIST_CREATE: 'time_sheet_list_create',
  OVER_TIME_SHEET_LIST_CREATE: 'over_time_sheet_list_create',
  OVER_TIME_SHEET_LIST_DETAIL: 'over_time_sheet_list_detail',
  EMPLOYEE_SHIFT_LIST_CREATE: 'employee_shift_list_create',
  EMPLOYEE_SHIFT_LIST_DETAIL: 'employee_shift_list_detail',
  EMPLOYEE_SHIFT_LIST_UPDATE: 'employee_shift_list_update',
  EMPLOYEE_SHIFT_LIST_DELETE: 'employee_shift_list_delete',
  EMPLOYEE_SHIFT_LIST_TIME_CONFIG: 'employee_shift_list_time_config',
  EMPLOYEE_SHIFT_LIST_OVERTIME_CONFIG: 'employee_shift_list_overtime_config',
  EMPLOYEE_SHIFT_LIST_SHIFT_SETUP: 'employee_shift_list_shift_setup',
  EMPLOYEE_SHIFT_LIST_EMPLOYEE_LIST: 'employee_shift_list_employee_list',
  DAY_OFF_LIST_CREATE: 'day_off_list_create',
  DAY_OFF_LIST_DETAIL: 'day_off_list_detail',
  DAY_OFF_LIST_UPDATE: 'day_off_list_update',
  DAY_OFF_LIST_DELETE: 'day_off_list_delete',
  LEAVE_CONFIG_LIST_CREATE: 'leave_config_list_create',
  LEAVE_CONFIG_LIST_UPDATE: 'leave_config_list_update',
  LEAVE_CONFIG_LIST_DETAIL: 'leave_config_list_detail',
  LEAVE_CONFIG_LIST_DELETE: 'leave_config_list_delete',
  LEAVE_CONFIG_LIST_VIEW_HISTORY: 'leave_config_list_view_history',
  EXTRA_ATTENDANCE_APPLICATION_LIST_CREATE:
    'extra_attendance_application_list_create',
  EXTRA_ATTENDANCE_APPLICATION_LIST_DETAIL:
    'extra_attendance_application_list_detail',
  EXTRA_ATTENDANCE_APPLICATION_LIST_UPDATE:
    'extra_attendance_application_list_update',
  EXTRA_ATTENDANCE_APPLICATION_LIST_DELETE:
    'extra_attendance_application_list_delete',
  OVERTIME_APPLICATION_LIST_CREATE: 'overtime_application_list_create',
  OVERTIME_APPLICATION_LIST_DETAIL: 'overtime_application_list_detail',
  OVERTIME_APPLICATION_LIST_UPDATE: 'overtime_application_list_update',
  OVERTIME_APPLICATION_LIST_DELETE: 'overtime_application_list_delete',
  LEAVE_APPLICATION_LIST_CREATE: 'leave_application_list_create',
  LEAVE_APPLICATION_LIST_DETAIL: 'leave_application_list_detail',
  LEAVE_APPLICATION_LIST_UPDATE: 'leave_application_list_update',
  LEAVE_APPLICATION_LIST_DELETE: 'leave_application_list_delete',
  PRE_LEAVE_APPLICATION_LIST_CREATE: 'pre_leave_application_list_create',
  PRE_LEAVE_APPLICATION_LIST_DETAIL: 'pre_leave_application_list_detail',
  PRE_LEAVE_APPLICATION_LIST_UPDATE: 'pre_leave_application_list_update',
  PRE_LEAVE_APPLICATION_LIST_DELETE: 'pre_leave_application_list_delete',
  BUSINESS_TRIP_APPLICATION_LIST_CREATE:
    'business_trip_application_list_create',
  BUSINESS_TRIP_APPLICATION_LIST_DETAIL:
    'business_trip_application_list_detail',
  BUSINESS_TRIP_APPLICATION_LIST_UPDATE:
    'business_trip_application_list_update',
  BUSINESS_TRIP_APPLICATION_LIST_DELETE:
    'business_trip_application_list_delete',
  OVERTIME_BREAK_LIST_DETAIL: 'overtime_break_list_detail',
  OVERTIME_BREAK_LIST_UPDATE: 'overtime_break_list_update',
  MANAGE_PAGE_CONFIG_FORM_CREATE: 'manage_page_config_form_create',
  MANAGE_PAGE_CONFIG_FORM_UPDATE: 'manage_page_config_form_update',
  MANAGE_PAGE_CONFIG_FORM_DETAIL: 'manage_page_config_form_detail',
  MANAGE_PAGE_CONFIG_FORM_DELETE: 'manage_page_config_form_delete',
  MANAGE_PAGE_CONFIG_FIELD_CREATE: 'manage_page_config_field_create',
  MANAGE_PAGE_CONFIG_FIELD_UPDATE: 'manage_page_config_field_update',
  MANAGE_PAGE_CONFIG_FIELD_DETAIL: 'manage_page_config_field_detail',
  MANAGE_PAGE_CONFIG_FIELD_DELETE: 'manage_page_config_field_delete',
  MANAGE_PAGE_CONFIG_FIELD: 'manage_page_config_field',
  SYSTEM_PAGE_TABLE_CONFIG_DETAIL: 'system_page_table_config_detail',
  SYSTEM_PAGE_TABLE_CONFIG_UPDATE: 'system_page_table_config_update',
  SYSTEM_PAGE_TABLE_CONFIG_DELETE: 'system_page_table_config_delete',
  SYSTEM_PAGE_TABLE_CONFIG_CREATE: 'system_page_table_config_create',
  SYSTEM_PAGE_TABLE_FIELD_CONFIG: 'system_page_table_field_config',
  MANAGE_PAGE_LIST_DETAIL: 'manage_page_list_detail',
  MANAGE_PAGE_LIST_CREATE: 'manage_page_list_create',
  MANAGE_PAGE_LIST_UPDATE: 'manage_page_list_update',
  MANAGE_PAGE_LIST_DELETE: 'manage_page_list_delete',
  MANAGE_PAGE_LIST_COPY_PAGE: 'manage_page_list_copy_page',
  MANAGE_PAGE_LIST_CONTROL: 'manage_page_list_control',
  MANAGE_PAGE_LIST_FORM: 'manage_page_list_form',
  MANAGE_PAGE_LIST_TABLE: 'manage_page_list_table',
  MANAGE_PAGE_LIST_SEARCH_FILTER: 'manage_page_list_search_filter',
  COLUMN_CONFIG_LIST_CREATE: 'column_config_list_create',
  COLUMN_CONFIG_LIST_DETAIL: 'column_config_list_detail',
  COLUMN_CONFIG_LIST_UPDATE: 'column_config_list_update',
  COLUMN_CONFIG_LIST_DELETE: 'column_config_list_delete',
  CONFIG_PERMISSION_LIST_CREATE: 'config_permission_list_create',
  CONFIG_PERMISSION_LIST_COPY: 'config_permission_list_copy',
  CONFIG_PERMISSION_LIST_SETTING: 'config_permission_list_setting',
  CONFIG_PERMISSION_LIST_UPDATE: 'config_permission_list_update',
  CONFIG_PERMISSION_LIST_DELETE: 'config_permission_list_delete',
  CONFIG_PERMISSION_LIST_DETAIL: 'config_permission_list_detail',
  CONTROL_CONFIG_LIST_CREATE: 'column_config_list_create',
  CONTROL_CONFIG_LIST_UPDATE: 'column_config_list_update',
  CONTROL_CONFIG_LIST_COPY: 'column_config_list_copy',
  CONTROL_CONFIG_LIST_DETAIL: 'column_config_list_detail',
  CONTROL_CONFIG_LIST_DELETE: 'column_config_list_delete',

  PURCHASE_MANAGEMENT_LIST_CREATE: 'purchase_management_list_create',
  PURCHASE_MANAGEMENT_LIST_DETAIL: 'purchase_management_list_detail',
  PURCHASE_MANAGEMENT_LIST_APPROVE: 'purchase_management_list_approve',
  PURCHASE_MANAGEMENT_LIST_REJECT: 'purchase_management_list_reject',
  PURCHASE_MANAGEMENT_LIST_UPDATE: 'purchase_management_list_update',
  PURCHASE_MANAGEMENT_LIST_DELETE: 'purchase_management_list_delete',
  CONTACT_MANAGEMENT_EMPLOYEE_LIST_CREATE:
    'contact_management_employee_list_create',
  CONTACT_MANAGEMENT_EMPLOYEE_LIST_UPDATE:
    'contact_management_employee_list_update',
  CONTACT_MANAGEMENT_EMPLOYEE_LIST_DETAIL:
    'contact_management_employee_list_detail',
  CONTACT_MANAGEMENT_EMPLOYEE_LIST_DELETE:
    'contact_management_employee_list_delete',
  PRODUCT_MANAGEMENT_CREATE: 'product_management_create',
  PRODUCT_MANAGEMENT_UPDATE: 'product_management_update',
  PRODUCT_MANAGEMENT_DELETE: 'product_management_delete',
  PRODUCT_MANAGEMENT_DETAIL: 'product_management_detail',
  PRODUCT_MANAGEMENT_APPROVE: 'product_management_approve',
  PRODUCT_MANAGEMENT_REJECT: 'product_management_reject',
  PRODUCT_MANAGEMENT_CHANGE_PRICE: 'product_management_change_price',
  PRODUCT_MANAGEMENT_HISTORY_TRADE: 'product_management_history_trade',
  PRODUCT_MANAGEMENT_CATEGORY_CREATE: 'product_management_category_create',
  PRODUCT_MANAGEMENT_CATEGORY_UPDATE: 'product_management_category_update',
  PRODUCT_MANAGEMENT_CATEGORY_DELETE: 'product_management_category_delete',
  PRODUCT_MANAGEMENT_CATEGORY_DETAIL: 'product_management_category_detail',
  PRODUCT_MANAGEMENT_BRAND_CREATE: 'product_management_brand_create',
  PRODUCT_MANAGEMENT_BRAND_DETAIL: 'product_management_brand_detail',
  PRODUCT_MANAGEMENT_BRAND_UPDATE: 'product_management_brand_update',
  PRODUCT_MANAGEMENT_BRAND_DELETE: 'product_management_brand_delete',
  PRODUCT_MANAGEMENT_UNIT_CREATE: 'product_management_unit_create',
  PRODUCT_MANAGEMENT_UNIT_UPDATE: 'product_management_unit_update',
  PRODUCT_MANAGEMENT_UNIT_DELETE: 'product_management_unit_delete',
  PRODUCT_MANAGEMENT_UNIT_DETAIL: 'product_management_unit_detail',
  PRICE_QUOTE_LIST_CREATE: 'price_quote_list_create',
  PRICE_QUOTE_LIST_UPDATE: 'contact_management_employee_list_update',
  PRICE_QUOTE_LIST_DELETE: 'contact_management_employee_list_delete',
  PRICE_QUOTE_LIST_DETAIL: 'contact_management_employee_list_detail',
  PRICE_QUOTE_LIST_APPROVE: 'contact_management_employee_list_approve',
  PRICE_QUOTE_LIST_REJECT: 'contact_management_employee_list_reject',
  PRICE_QUOTE_LIST_ORDER: 'contact_management_employee_list_order',
};

export const PAGE_TABLE_OBJECT_TYPE = {
  EMPLOYEE_LIST: 'employee_list',
  INSURANCE_LIST: 'insurance_list',
  CONTRACT_LIST: 'contract_list',
  SALARY_LIST: 'salary_list',
  EMPLOYEE_GROUP_LIST: 'employee_group_list',
  PLANS_LIST: 'plans_list',
  CRITERIA_LIST: 'criteria_list',
  CANDIDATE_LIST: 'candidate_list',
  POSITION_LIST: 'position_list',
  NEEDS_LIST: 'needs_list',
  TIME_SHEET_LIST: 'time_sheet_list',
  OVER_TIME_SHEET_LIST: 'over_time_sheet_list',
  EMPLOYEE_SHIFT_LIST: 'employee_shift_list',
  DAY_OFF_LIST: 'day_off_list',
  EXTRA_ATTENDANCE_APPLICATION: 'employee_list',
};
